module.exports = [
  {
    text: "基础",
    link: "/articles/project/webpack/intro/",
    items: [
        { text: "base", link: "/articles/project/webpack/base/base" },
        { text: "config", link: "/articles/project/webpack/base/config" },
        { text: "development", link: "/articles/project/webpack/base/development" },
        { text: "css", link: "/articles/project/webpack/base/css" },
        { text: "image", link: "/articles/project/webpack/base/image" },
        { text: "output", link: "/articles/project/webpack/base/output" },
        { text: "clean", link: "/articles/project/webpack/base/clean" },
        { text: "font", link: "/articles/project/webpack/base/font" },
        { text: "other", link: "/articles/project/webpack/base/other" },
        { text: "javascript", link: "/articles/project/webpack/base/javascript" },
        { text: "html", link: "/articles/project/webpack/base/html" },
        { text: "server", link: "/articles/project/webpack/base/server" },
        { text: "production", link: "/articles/project/webpack/base/production" },
        { text: "optimizeCss", link: "/articles/project/webpack/base/optimizeCss" },
        { text: "minifyHtml", link: "/articles/project/webpack/base/minifyHtml" },
        { text: "summary", link: "/articles/project/webpack/base/summary" },
    ],
  },
  {
    text: "高级",
    link: "/articles/project/webpack/intro/",
    items: [
      { text: "base", link: "/articles/project/webpack/intro/base" },
      { text: "config", link: "/articles/project/webpack/intro/config" },
    ],
  },
  {
    text: "项目",
    link: "/articles/project/webpack/intro/",
    items: [
      { text: "base", link: "/articles/project/webpack/base/base" },
      { text: "config", link: "/articles/project/webpack/base/config" },
      { text: "development", link: "/articles/project/webpack/base/development" },
      { text: "css", link: "/articles/project/webpack/base/css" },
      { text: "image", link: "/articles/project/webpack/base/image" },
      { text: "output", link: "/articles/project/webpack/base/output" },
      { text: "clean", link: "/articles/project/webpack/base/clean" },
      { text: "font", link: "/articles/project/webpack/base/font" },
      { text: "other", link: "/articles/project/webpack/base/other" },
      { text: "javascript", link: "/articles/project/webpack/base/javascript" },
      { text: "html", link: "/articles/project/webpack/base/html" },
      { text: "server", link: "/articles/project/webpack/base/server" },
      { text: "production", link: "/articles/project/webpack/base/production" },
      { text: "optimizeCss", link: "/articles/project/webpack/base/optimizeCss" },
      { text: "minifyHtml", link: "/articles/project/webpack/base/minifyHtml" },
      { text: "summary", link: "/articles/project/webpack/base/summary" },
    ],
  },
  {
    text: "原理",
    link: "/articles/project/webpack/intro/",
    items: [
      { text: "base", link: "/articles/project/webpack/intro/base" },
      { text: "config", link: "/articles/project/webpack/intro/config" },
    ],
  },
];
